export const Messages = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    USER_BLOCKED: "Your are blocked from Skillora",
    USER_NOT_FOUND: "User not found, try to signup",
    OTP_SENT: "OTP has been sent",
    OTP_RESENT: "OTP has been resent successfully",
    OTP_VERIFIED: "OTP verification successful",
    OTP_EXPIRED: "Your OTP has been expired, try again",
    INCORRECT_OTP: "The OTP you provided is incorrect",
    NAME_REQUIRED: "Name is required",
    EMAIL_REQUIRED: "Email is required",
    NO_ACCESS: "Unauthorized Access",
    TOKEN_REQUIRED: "Access denied. No token provided.",
    BLOCKED: "User blocked successfully",
    UNBLOCKED: "User unblocked successfully",
    INVALID_TOKEN: "Invalid authentication token.",
    INVALID_BIO: "Bio should contains 100 - 600 characters",
    INVALID_FILE_TYPE: "Only jpeg, jpg, webp and png files allowed",
    INVALID_ROLE: "Invalid role",
    INVALID_NAME: "Please enter a valid name (A - Z)",
    INVALID_EMAIL: "Please enter a valid email",
    INVALID_REQUEST: "Invalid Request",
    INVALID_CREDENTIALS: "Invalid password or email",
    PASSWORD_RESET_SUCCESS: "Your password has been reset successfully",
    PASSWORD_RESET_FAILED: "Password reset failed, try again later",
    PASSWORD_REQUIRED: "Password is required",
    PASSWORD_LENGTH: "Your password must be at least 8 characters long",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    LOGIN_SUCCESS: "Login successful",
    LOGOUT_SUCCESS: "Logout successful",
    SIGNUP_SUCCESS: "Signup successful",
    CATEGORY_NOT_FOUND: "Category not found",
    CATEGORY_EXIST: "Category already exists",
    SKILLS_NOT_FOUND: "Skills not found",
    SKILLS_EXIST: "Skill already exists",
    CATEGORY_LISTED: "Category listed successfully",
    CATEGORY_UNLISTED: "Category unlisted successfully",
    SKILLS_LISTED: "Skills listed successfully",
    SKILLS_UNLISTED: "Skils unlisted successfully"
}